baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hello-friend-ng"
paginate = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Software engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Nacho's homepage"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Uncomment this if you want a portrait on your start page
  [params.portrait]
    path     = "img/nachogoca.jpg"
    alt      = "Portrait"
    maxWidth = "300"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:nacho.gon.car@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/nachogoca"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/gocaignacio"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Nacho Gonz√°lez"
    subtitle = "Nacho Gonzalez website"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"